title: Swapnil Tayde
logo: docs/assets/Swapnil_Tayde_1000x1000.jpg
description: Curious, Disciplined, Driven Data Learner who wants to help in turning raw data into actionable insights.
#show_downloads: true
theme: jekyll-theme-minimal
